#theme: jekyll-theme-minimal
theme: jekyll-theme-tactile
# theme: jekyll-theme-primer
repository: blekenbleu/blekenbleu.github.io
#github: [metadata]
#markdown: CommonMarkGhPages
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blekenbleu.github.io/" # the base hostname & protocol for your site
